// Indian states + UTs — canonical list shared by both the customer
// booking form and the rep app's edit-profile picker so the chosen
// value matches across surfaces.
export const INDIAN_STATES: string[] = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
  'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka',
  'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
  'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
  'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
  // Union Territories
  'Andaman and Nicobar Islands', 'Chandigarh', 'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi', 'Jammu and Kashmir', 'Ladakh', 'Lakshadweep', 'Puducherry',
];

// Flat searchable list of Indian districts, alphabetized.
// Used by the booking form's district picker so users select from a
// canonical list instead of typing/typoing district names that then
// fail government-form validation downstream.
//
// Not exhaustive — covers the common districts users in our target
// metros actually pick. The picker also has an "Other (type below)"
// affordance for the long tail.
export const INDIAN_DISTRICTS: string[] = [
  'Adilabad', 'Agra', 'Ahmedabad', 'Ahmednagar', 'Aizawl', 'Ajmer', 'Akola',
  'Alappuzha', 'Aligarh', 'Alipurduar', 'Allahabad (Prayagraj)', 'Almora',
  'Alwar', 'Ambala', 'Amravati', 'Amreli', 'Amritsar', 'Anand', 'Anantapur',
  'Anantnag', 'Angul', 'Araria', 'Aurangabad', 'Azamgarh', 'Bagalkot',
  'Bageshwar', 'Baghpat', 'Bahraich', 'Baksa', 'Balaghat', 'Balangir',
  'Ballia', 'Balod', 'Balrampur', 'Banaskantha', 'Banda', 'Bangalore Rural',
  'Bangalore Urban', 'Banka', 'Bankura', 'Banswara', 'Barabanki', 'Baramulla',
  'Baran', 'Bardhaman', 'Bareilly', 'Bargarh', 'Barmer', 'Barnala', 'Barpeta',
  'Bastar', 'Basti', 'Bathinda', 'Beed', 'Begusarai', 'Belgaum (Belagavi)',
  'Bellary (Ballari)', 'Bemetara', 'Betul', 'Bhadohi', 'Bhadrak', 'Bhagalpur',
  'Bhandara', 'Bharatpur', 'Bharuch', 'Bhavnagar', 'Bhilwara', 'Bhind',
  'Bhiwadi', 'Bhiwani', 'Bhojpur', 'Bhopal', 'Bidar', 'Bijapur', 'Bijnor',
  'Bikaner', 'Bilaspur', 'Birbhum', 'Bishnupur', 'Bokaro', 'Bongaigaon',
  'Boudh', 'Budaun', 'Budgam', 'Bulandshahr', 'Buldhana', 'Bundi', 'Burhanpur',
  'Buxar', 'Cachar', 'Central Delhi', 'Chamarajanagar', 'Chamba', 'Chamoli',
  'Champawat', 'Champhai', 'Chandauli', 'Chandel', 'Chandigarh', 'Chandrapur',
  'Changlang', 'Charkhi Dadri', 'Chatra', 'Chennai', 'Chhatarpur', 'Chhindwara',
  'Chhota Udaipur', 'Chikballapur', 'Chikkamagaluru', 'Chitradurga',
  'Chittoor', 'Chittorgarh', 'Churachandpur', 'Churu', 'Coimbatore', 'Cooch Behar',
  'Cuddalore', 'Cuttack', 'Dahod', 'Dakshina Kannada', 'Dakshin Dinajpur',
  'Daman', 'Damoh', 'Dang', 'Dantewada', 'Darbhanga', 'Darjeeling', 'Darrang',
  'Datia', 'Dausa', 'Davangere', 'Dehradun', 'Deogarh', 'Deoghar', 'Deoria',
  'Dewas', 'Dhalai', 'Dhamtari', 'Dhanbad', 'Dhar', 'Dharmapuri', 'Dharwad',
  'Dhemaji', 'Dhenkanal', 'Dholpur', 'Dhubri', 'Dhule', 'Dibang Valley',
  'Dibrugarh', 'Dimapur', 'Dindigul', 'Dindori', 'Diu', 'Doda', 'Dumka',
  'Dungarpur', 'Durg', 'East Champaran', 'East Delhi', 'East Garo Hills',
  'East Godavari', 'East Jaintia Hills', 'East Kameng', 'East Khasi Hills',
  'East Siang', 'East Sikkim', 'East Singhbhum', 'Eluru', 'Ernakulam',
  'Erode', 'Etah', 'Etawah', 'Faizabad (Ayodhya)', 'Faridabad', 'Faridkot',
  'Farrukhabad', 'Fatehabad', 'Fatehgarh Sahib', 'Fatehpur', 'Fazilka',
  'Firozabad', 'Firozpur', 'Gadag', 'Gadchiroli', 'Gajapati', 'Ganderbal',
  'Gandhinagar', 'Ganganagar', 'Ganjam', 'Garhwa', 'Gariaband', 'Gautam Buddha Nagar',
  'Gaya', 'Ghaziabad', 'Ghazipur', 'Giridih', 'Goalpara', 'Godda', 'Golaghat',
  'Gomati', 'Gonda', 'Gondia', 'Gopalganj', 'Gorakhpur', 'Gulbarga (Kalaburagi)',
  'Gumla', 'Guna', 'Guntur', 'Gurdaspur', 'Gurgaon (Gurugram)', 'Gwalior',
  'Hailakandi', 'Hamirpur', 'Hanumangarh', 'Hapur', 'Harda', 'Hardoi',
  'Haridwar', 'Hassan', 'Hathras', 'Haveri', 'Hazaribagh', 'Hingoli', 'Hisar',
  'Hooghly', 'Hoshangabad', 'Hoshiarpur', 'Howrah', 'Hyderabad', 'Idukki',
  'Imphal East', 'Imphal West', 'Indore', 'Jabalpur', 'Jagatsinghpur', 'Jagtial',
  'Jaipur', 'Jaisalmer', 'Jajpur', 'Jalandhar', 'Jalaun', 'Jalgaon', 'Jalna',
  'Jalore', 'Jalpaiguri', 'Jammu', 'Jamnagar', 'Jamtara', 'Jamui', 'Janjgir-Champa',
  'Jashpur', 'Jaunpur', 'Jehanabad', 'Jhabua', 'Jhajjar', 'Jhalawar', 'Jhansi',
  'Jharsuguda', 'Jhunjhunu', 'Jind', 'Jodhpur', 'Jogulamba Gadwal', 'Jorhat',
  'Junagadh', 'Jyotiba Phule Nagar', 'Kabirdham', 'Kachchh', 'Kadapa', 'Kaimur',
  'Kaithal', 'Kakinada', 'Kalahandi', 'Kalimpong', 'Kallakurichi', 'Kamareddy',
  'Kamrup', 'Kamrup Metropolitan', 'Kanchipuram', 'Kandhamal', 'Kangra', 'Kanker',
  'Kannauj', 'Kannur', 'Kanpur Dehat', 'Kanpur Nagar', 'Kanyakumari', 'Kapurthala',
  'Karaikal', 'Karauli', 'Karbi Anglong', 'Kargil', 'Karimganj', 'Karimnagar',
  'Karnal', 'Karur', 'Kasaragod', 'Kasganj', 'Kathua', 'Katihar', 'Katni',
  'Kaushambi', 'Kendrapara', 'Kendujhar (Keonjhar)', 'Khagaria', 'Khammam',
  'Khandwa', 'Khargone', 'Kheda', 'Khordha', 'Khowai', 'Khunti', 'Kinnaur',
  'Kiphire', 'Kishanganj', 'Kishtwar', 'Kodagu', 'Koderma', 'Kohima', 'Kokrajhar',
  'Kolar', 'Kolasib', 'Kolhapur', 'Kolkata', 'Kollam', 'Komaram Bheem', 'Koppal',
  'Koraput', 'Korba', 'Koriya', 'Kota', 'Kottayam', 'Kozhikode', 'Krishna',
  'Krishnagiri', 'Kullu', 'Kulgam', 'Kupwara', 'Kurnool', 'Kurukshetra',
  'Kurung Kumey', 'Kushinagar', 'Kutch', 'Lahaul and Spiti', 'Lakhimpur',
  'Lakhimpur Kheri', 'Lakhisarai', 'Lakshadweep', 'Lalitpur', 'Latehar', 'Latur',
  'Lawngtlai', 'Leh', 'Lohardaga', 'Lohit', 'Longding', 'Longleng', 'Lower Dibang Valley',
  'Lower Siang', 'Lower Subansiri', 'Lucknow', 'Ludhiana', 'Lunglei', 'Madhepura',
  'Madhubani', 'Madurai', 'Mahabubabad', 'Mahabubnagar', 'Maharajganj', 'Mahasamund',
  'Mahbubnagar', 'Mahe', 'Mahendragarh', 'Mahisagar', 'Mahoba', 'Mainpuri',
  'Malappuram', 'Malda', 'Malkangiri', 'Mamit', 'Mancherial', 'Mandi', 'Mandla',
  'Mandsaur', 'Mandya', 'Mansa', 'Mathura', 'Mau', 'Mayurbhanj', 'Medak',
  'Medchal-Malkajgiri', 'Meerut', 'Mehsana', 'Mewat (Nuh)', 'Mirzapur', 'Moga',
  'Mokokchung', 'Mon', 'Moradabad', 'Morbi', 'Morena', 'Morigaon', 'Muktsar',
  'Mumbai City', 'Mumbai Suburban', 'Munger', 'Murshidabad', 'Muzaffarnagar',
  'Muzaffarpur', 'Mysore (Mysuru)', 'Nabarangpur', 'Nadia', 'Nagaon', 'Nagapattinam',
  'Nagarkurnool', 'Nagaur', 'Nagpur', 'Nainital', 'Nalanda', 'Nalbari', 'Nalgonda',
  'Namakkal', 'Namsai', 'Nanded', 'Nandurbar', 'Narayanpur', 'Narmada', 'Narsinghpur',
  'Nashik', 'Navsari', 'Nawada', 'Nawanshahr', 'Nayagarh', 'Neemuch', 'Nellore',
  'New Delhi', 'Nicobar', 'Nilgiris', 'Nirmal', 'Nizamabad', 'North 24 Parganas',
  'North Delhi', 'North East Delhi', 'North Goa', 'North Sikkim', 'North Tripura',
  'North West Delhi', 'Nuapada', 'Osmanabad', 'Pakur', 'Palakkad', 'Palamu',
  'Palghar', 'Pali', 'Palwal', 'Panchkula', 'Panchmahal', 'Panipat', 'Panna',
  'Papum Pare', 'Parbhani', 'Paschim Bardhaman', 'Paschim Medinipur', 'Patan',
  'Pathanamthitta', 'Pathankot', 'Patiala', 'Patna', 'Pauri Garhwal', 'Peddapalli',
  'Perambalur', 'Peren', 'Phek', 'Pilibhit', 'Pithoragarh', 'Poonch', 'Porbandar',
  'Prakasam', 'Pratapgarh', 'Puducherry', 'Pudukkottai', 'Pulwama', 'Pune',
  'Purbi Singhbhum', 'Puri', 'Purnia', 'Purulia', 'Raebareli', 'Raichur',
  'Raigad', 'Raigarh', 'Raipur', 'Raisen', 'Rajauri', 'Rajgarh', 'Rajkot',
  'Rajnandgaon', 'Rajsamand', 'Ramanagara', 'Ramanathapuram', 'Ramban',
  'Ramgarh', 'Rampur', 'Ranchi', 'Ranga Reddy', 'Ranipet', 'Ratlam', 'Ratnagiri',
  'Rayagada', 'Reasi', 'Rewa', 'Rewari', 'Ri Bhoi', 'Rohtak', 'Rohtas', 'Rudraprayag',
  'Rupnagar', 'Sabarkantha', 'Sagar', 'Saharanpur', 'Saharsa', 'Sahibganj',
  'Sahibzada Ajit Singh Nagar (Mohali)', 'Saiha', 'Salem', 'Samastipur', 'Samba',
  'Sambalpur', 'Sambhal', 'Sangareddy', 'Sangli', 'Sangrur', 'Sant Kabir Nagar',
  'Saran', 'Satara', 'Satna', 'Sawai Madhopur', 'Sehore', 'Senapati', 'Seoni',
  'Seraikela-Kharsawan', 'Serchhip', 'Shahdara', 'Shahdol', 'Shahjahanpur',
  'Shajapur', 'Shamli', 'Sheikhpura', 'Sheohar', 'Sheopur', 'Shimla', 'Shimoga (Shivamogga)',
  'Shivpuri', 'Shopian', 'Shravasti', 'Siddharthnagar', 'Siddipet', 'Sidhi',
  'Sikar', 'Simdega', 'Sindhudurg', 'Singrauli', 'Sirmaur', 'Sirohi', 'Sirsa',
  'Sitamarhi', 'Sitapur', 'Sivaganga', 'Sivasagar', 'Siwan', 'Solan', 'Solapur',
  'Sonbhadra', 'Sonipat', 'Sonitpur', 'South 24 Parganas', 'South Andaman',
  'South Delhi', 'South East Delhi', 'South Garo Hills', 'South Goa',
  'South Salmara-Mankachar', 'South Sikkim', 'South Tripura', 'South West Delhi',
  'South West Garo Hills', 'South West Khasi Hills', 'Sri Muktsar Sahib',
  'Sri Potti Sriramulu Nellore', 'Srikakulam', 'Srinagar', 'Subarnapur',
  'Sukma', 'Sultanpur', 'Sundargarh', 'Supaul', 'Surajpur', 'Surat',
  'Surendranagar', 'Surguja', 'Suryapet', 'Tamenglong', 'Tapi', 'Tarn Taran',
  'Tawang', 'Tehri Garhwal', 'Tenkasi', 'Thane', 'Thanjavur', 'The Dangs',
  'Theni', 'Thiruvananthapuram', 'Thiruvarur', 'Thoothukudi (Tuticorin)',
  'Thoubal', 'Thrissur', 'Tikamgarh', 'Tinsukia', 'Tirap', 'Tiruchirappalli',
  'Tirunelveli', 'Tirupathur', 'Tiruppur', 'Tiruvallur', 'Tiruvannamalai',
  'Tonk', 'Tuensang', 'Tumkur (Tumakuru)', 'Udaipur', 'Udalguri',
  'Udham Singh Nagar', 'Udhampur', 'Udupi', 'Ujjain', 'Ukhrul', 'Umaria',
  'Una', 'Unakoti', 'Unnao', 'Upper Siang', 'Upper Subansiri', 'Uttar Dinajpur',
  'Uttara Kannada', 'Uttarkashi', 'Vadodara', 'Vaishali', 'Valsad', 'Varanasi',
  'Vellore', 'Vidisha', 'Vijayapura', 'Vikarabad', 'Viluppuram', 'Virudhunagar',
  'Visakhapatnam', 'Vizianagaram', 'Wanaparthy', 'Warangal Rural', 'Warangal Urban',
  'Wardha', 'Washim', 'Wayanad', 'West Champaran', 'West Delhi', 'West Garo Hills',
  'West Godavari', 'West Jaintia Hills', 'West Kameng', 'West Karbi Anglong',
  'West Khasi Hills', 'West Siang', 'West Sikkim', 'West Singhbhum', 'West Tripura',
  'Wokha', 'Yadadri Bhuvanagiri', 'Yadgir', 'Yamunanagar', 'Yanam', 'Yavatmal',
  'Zunheboto',
];
