// Expo config plugin: marks SYSTEM_ALERT_WINDOW as `tools:node="remove"` in
// the merged Android manifest. Some transitive Expo / React Native module
// auto-merges this permission ("Display over other apps"), which is
// genuinely sensitive — Play Console reviewers ask for written
// justification or reject outright. This app never draws system overlays
// (no chat heads, no PiP, no floating widgets), so we strip the request.
//
// Why a plugin (rather than hand-editing AndroidManifest.xml): the
// android/ folder is gitignored and regenerated by `expo prebuild` from
// app.json + plugins. A direct manifest edit survives until the next
// prebuild, then vanishes. This plugin re-applies the override on every
// prebuild so the source of truth stays in app.json/plugins/.

const { withAndroidManifest } = require('@expo/config-plugins');

const PERMISSION = 'android.permission.SYSTEM_ALERT_WINDOW';

const withRemoveSystemAlertWindow = (config) =>
  withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults.manifest;
    manifest.$ = manifest.$ || {};
    if (!manifest.$['xmlns:tools']) {
      manifest.$['xmlns:tools'] = 'http://schemas.android.com/tools';
    }
    manifest['uses-permission'] = manifest['uses-permission'] || [];
    const list = manifest['uses-permission'];
    const existing = list.find((p) => p?.$?.['android:name'] === PERMISSION);
    if (existing) {
      existing.$['tools:node'] = 'remove';
    } else {
      list.push({
        $: {
          'android:name': PERMISSION,
          'tools:node': 'remove',
        },
      });
    }
    return cfg;
  });

module.exports = withRemoveSystemAlertWindow;
