// Expo config plugin: marks RECORD_AUDIO as `tools:node="remove"` in the
// merged Android manifest. expo-camera's library manifest auto-merges
// RECORD_AUDIO in (it ships with video-with-audio capture support),
// but this customer app only uses the camera for still document photos
// — never audio/video. We strip the permission so Play Console review
// doesn't flag a microphone capability the app doesn't actually use,
// and so users don't see a mic-permission ask at install time.
//
// Why a plugin (rather than hand-editing AndroidManifest.xml): the
// android/ folder is gitignored and regenerated by `expo prebuild` from
// app.json + plugins. A direct manifest edit survives until the next
// prebuild, then vanishes. This plugin re-applies the override on
// every prebuild so the source of truth stays in app.json/plugins/.

const { withAndroidManifest } = require('@expo/config-plugins');

const PERMISSION = 'android.permission.RECORD_AUDIO';

const withRemoveAudioPermission = (config) =>
  withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults.manifest;
    manifest.$ = manifest.$ || {};
    if (!manifest.$['xmlns:tools']) {
      manifest.$['xmlns:tools'] = 'http://schemas.android.com/tools';
    }
    manifest['uses-permission'] = manifest['uses-permission'] || [];
    const list = manifest['uses-permission'];
    const existing = list.find((p) => p?.$?.['android:name'] === PERMISSION);
    if (existing) {
      existing.$['tools:node'] = 'remove';
    } else {
      list.push({
        $: {
          'android:name': PERMISSION,
          'tools:node': 'remove',
        },
      });
    }
    return cfg;
  });

module.exports = withRemoveAudioPermission;
